In [1]:
import numpy as np  
import pandas as pd  

In [2]:
df = pd.read_csv("/kaggle/input/banking-dataset-marketing-targets/train.csv", sep=';')
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [3]:
df.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [5]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [6]:
df.duplicated().sum()

0

In [7]:
df.nunique()

age            77
job            12
marital         3
education       4
default         2
balance      7168
housing         2
loan            2
contact         3
day            31
month          12
duration     1573
campaign       48
pdays         559
previous       41
poutcome        4
y               2
dtype: int64

In [8]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [9]:
pip install dataprep

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.6/152.6 kB 3.6 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 55.8 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of dask[array,dataframe,delayed] to determine which version is compatible with other requirements. This could take a while.
INFO: pip is still looking at multiple versions of dask[array,dataframe,delayed] to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of flask to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dask-expr to determine which version is compatible with other requirements. This could take a while.
INFO: pip is still looking at multiple versions of dask-expr to determine which version is compatible with other 

In [11]:
from dataprep.eda import create_report

report = create_report(df)
report.show()

/opt/conda/lib/python3.10/site-packages/dask/dataframe/core.py:3929: UserWarning: Dask currently has limited support for converting pandas extension dtypes to arrays. Converting int64[pyarrow] to object dtype.
  warnings.warn(
error happended in column:job


ValueError: Metadata inference failed in `mul`.

Original error is below:
------------------------
TypeError("values should be integer numpy array. Use the 'pd.array' function instead")

Traceback:
---------
  File "/opt/conda/lib/python3.10/site-packages/dask/dataframe/utils.py", line 194, in raise_on_meta_error
    yield
  File "/opt/conda/lib/python3.10/site-packages/dask/dataframe/core.py", line 6850, in elemwise
    meta = partial_by_order(*parts, function=op, other=other)
  File "/opt/conda/lib/python3.10/site-packages/dask/utils.py", line 1476, in partial_by_order
    return function(*args2, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/ops/common.py", line 76, in new_method
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/arraylike.py", line 202, in __mul__
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/series.py", line 6135, in _arith_method
    axis=axis,
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/base.py", line 1382, in _arith_method
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 273, in arithmetic_op
    res_values = op(lvalues, rvalues)
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/ops/common.py", line 76, in new_method
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/arraylike.py", line 202, in __mul__
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/arrays/masked.py", line 808, in _arith_method
    )
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/arrays/masked.py", line 893, in _maybe_mask_result
    na_sentinel_arg = -1 if resolved_na_sentinel is None else resolved_na_sentinel
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/arrays/numeric.py", line 251, in __init__
    @classmethod


In [12]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
le = LabelEncoder()

categorical_columns = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome', 'y']

for column in categorical_columns:
  #if column != 'y':
    df[column] = le.fit_transform(df[column])

display(df.head())

age  job  marital  education  default  balance  housing  loan  contact  \
0   58    4        1          2        0     2143        1     0        2   
1   44    9        2          1        0       29        1     0        2   
2   33    2        1          1        0        2        1     1        2   
3   47    1        1          3        0     1506        1     0        2   
4   33   11        2          3        0        1        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  y  
0    5      8       261         1     -1         0         3  0  
1    5      8       151         1     -1         0         3  0  
2    5      8        76         1     -1         0         3  0  
3    5      8        92         1     -1         0         3  0  
4    5      8       198         1     -1         0         3  0

In [13]:
print(df['y'].value_counts())

y
0    39922
1     5289
Name: count, dtype: int64


In [14]:
print(df.shape)

(45211, 17)


In [15]:
X=df.drop(columns=['y'],axis=1)
y=df['y']

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=45)

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Model
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

# Predictions
y_pred = log_reg.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8916228918993642
Confusion Matrix:
 [[15717   272]
 [ 1688   408]]
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.98      0.94     15989
           1       0.60      0.19      0.29      2096

    accuracy                           0.89     18085
   macro avg       0.75      0.59      0.62     18085
weighted avg       0.87      0.89      0.87     18085



/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [18]:
from sklearn.ensemble import RandomForestClassifier

# Model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Predictions
y_pred = rf_model.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9087088747580868
Confusion Matrix:
 [[15534   455]
 [ 1196   900]]
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.97      0.95     15989
           1       0.66      0.43      0.52      2096

    accuracy                           0.91     18085
   macro avg       0.80      0.70      0.74     18085
weighted avg       0.90      0.91      0.90     18085



In [20]:
from sklearn.neighbors import KNeighborsClassifier

# Model
knn_model = KNeighborsClassifier(n_neighbors=16)
knn_model.fit(X_train, y_train)

# Predictions
y_pred = knn_model.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8865358031517833
Confusion Matrix:
 [[15651   338]
 [ 1714   382]]
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.98      0.94     15989
           1       0.53      0.18      0.27      2096

    accuracy                           0.89     18085
   macro avg       0.72      0.58      0.60     18085
weighted avg       0.86      0.89      0.86     18085



In [31]:
import xgboost as xgb
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# ... (Data preparation)

# Create DMatrix
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Define parameters
param = {
    'max_depth': 3,
    'eta': 0.3,
    'objective': 'multi:softmax',
    'num_class': len(np.unique(y_train))
}

# Train the model
try:
    model = xgb.train(param, dtrain, num_boost_round=200)
except ValueError as e:
    print("Error during training:", e)
    # Handle the error, e.g., print a detailed error message or try alternative approaches

# Make predictions
try:
    y_pred = model.predict(dtest)
except ValueError as e:
    print("Error during prediction:", e)
    # Handle the error, e.g., check feature names and data types

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9085429914293613
Confusion Matrix:
 [[15448   541]
 [ 1113   983]]
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.97      0.95     15989
           1       0.65      0.47      0.54      2096

    accuracy                           0.91     18085
   macro avg       0.79      0.72      0.75     18085
weighted avg       0.90      0.91      0.90     18085



Random forest classifier and xgboost performance is 90% accuracy